const RequestActionTypes = {
    SAVE_REQUEST_START: "SAVE_REQUEST_START",
    SAVE_REQUEST_SUCCESS: "SAVE_REQUEST_SUCCESS",
    SAVE_REQUEST_FAIL: "SAVE_REQUEST_FAIL",
    FETCH_REQUEST_START: "FETCH_REQUEST_START",
    FETCH_REQUEST_SUCCESS: "FETCH_REQUEST_SUCCESS",
    FETCH_REQUEST_FAIL: "FETCH_REQUEST_FAIL",
    FEEDBACK_REQUEST_START: "FEEDBACK_REQUEST_START",
    FEEDBACK_REQUEST_SUCCESS: "FEEDBACK_REQUEST_SUCCESS",
    FEEDBACK_REQUEST_FAIL: "FEEDBACK_REQUEST_FAIL",
    SYNC_POOL_DATA: "SYNC_POOL_DATA"
};

export default RequestActionTypes;
