const GeofirestoreActionTypes = {
    FIND_NEAREST_START: "FIND_NEAREST_START",
    FIND_NEAREST_SUCCESS: "FIND_NEAREST_SUCCESS",
    FIND_NEAREST_FAIL: "FIND_NEAREST_FAIL",
    CLEAR_DRIVERS: "CLEAR_DRIVERS",
    CLEAN_UP: "CLEAN_UP"
};

export default GeofirestoreActionTypes;
