export const message = {
    phoneExisted: "* Số điện thoại đã được đăng ký",
    phoneUnexisted: "* Số điện thoại chưa được đăng ký",
    invalidPhone: "* Số điện thoại không hợp lệ",
    invalidPassword: "* Mật khẩu cần ít nhất 6 kí tự",
    invalidConfirmPassword: "* Xác nhận mật khẩu không khớp",
    invalidName: "* Tên không hợp lệ",
    cancelRequest: "Các thông tin ở lần gửi yêu cầu này sẽ không được lưu giữ cho lần gửi yêu cầu tiếp theo.",
    401: "Tên tài khoản và mật khẩu bạn cung cấp không đúng, vui lòng kiểm tra lại!",
    202: "Cập nhật thông tin cá nhân thành công!",
    203: "Cập nhật thông tin sức khỏe thành công!",
    204: "Hủy yêu cầu thành công. Bạn có thể xem lại trong phần Lịch sử!",
    205: "Tạo yêu cầu thành công",
    402: "Cập nhật thông tin cá nhân không thành công!",
    403: "Cập nhật thông tin sức khỏe không thành công!",
    404: "Hệ thống ghi nhận địa chỉ để tạo yêu cầu không hợp lệ, vui lòng kiểm tra lại!",
    405: "Đây có thể là do lỗi kỹ thuật mà chúng tôi đang khắc phục. Hãy thử thực hiện lại chức năng này!",
    406: "Vui lòng cung cấp các thông tin có dấu (*) để hoàn thiện hồ sơ!",
    700: "Phiên làm việc hết hạn, vui lòng đăng xuất để kiểm tra hoạt động!",
};
